
solon.app:
  name: demoapp
  group: demo

solon.cloud.local:
  discovery:
    service:
      hellorpc:
        - http://localhost:8081


io:
  opentracing:
    trace:
      host: localhost
      port: 6831