server.port: 7112

solon.app:
  group: demo
  name: helloapi    #发现服务使用的应用名（在Demo，将被NimaClient引用）

solon.cloud.zookeeper:
  server: "localhost:2181"

solon.logging.logger:
  "org.apache.zookeeper.*":
    level: "WARN"