server.port: 8081

solon.app:
  name: hellorpc
  group: demo

io:
  opentracing:
    trace:
      host: localhost
      port: 6831

#solon.logging.logger:
#  "io.jaegertracing.*":
#    level: WARN
#  "org.noear.*":
#    level: INFO